services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile  # this is optional if the file is named Dockerfile and is in the same directory as the docker-compose.yml
    container_name: custom-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    image: olubebubechukwu/custom-nodeapp:latest

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example